---
routers:
  RTR1: 2001:DB8:c005:4fff::178
  RTR2: 2001:DB8:c005:4fff::178
  RTR3: 2001:DB8:c009:cfff::9999
  
credentials:
  username: netconf
  path2keyfile: /home/user/.ssh/netconf

startnode:
  label: Starting AS
  color: green
  fontcolor: blue
  style: filled

graphopts:
  dumpplot: False
  strict: True
  edgecolor: False
  firsthop: False
  lasthop: False
