---
routers:
  ACAD: 2620:106:c005:4fff:ffff:ffff:ffff:178
  SUPP: 2620:106:c005:4fff:ffff:ffff:ffff:178
  NVA: 2620:106:c009:cfff:ffff:ffff:ffff:9999
  
credentials:
  username: netconf
  path2keyfile: /home/agallo/.ssh/netconf

startnode:
  label: GW
  color: cornflowerblue
  fontcolor: lightgoldenrod
  style: filled

graphopts:
  dumpplot: False
  strict: True
  coloredge: True
  firsthop: False
  lasthop: False
